name: Build Kernel

on:
  workflow_dispatch:
  
jobs:
  build_kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git bison flex libxml2 libssl-dev bc zip default-jre python3 python3-pip wget curl cpio bash python2
      
      - name: Build kernel
        run: |
          git clone -b 15.0 https://github.com/sajidshahriar72543/memetroll-karnul.git  --depth=1
          cd memetroll-karnul
          sh build.sh --clang
    env:
      token: ${{ secrets.TGID }}
      chat_id: ${{ secrets.BOTID }}